config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
                  url(r'^about/$',
                      TemplateView.as_view(template_name='pages/about.html'),
                      name='about'),
                  url(r'^grappelli/', include('grappelli.urls')),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, admin.site.urls),

                  # User management
                  url(r'^users/',
                      include('vien_nchl.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),
                  # Your stuff: custom urls includes go here

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    url(r'^', include('vien_nchl.web.urls', namespace='web')),
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns

vien_nchl/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

vien_nchl/web/urls.py
from django.conf.urls import url

from vien_nchl.web.views import HomePage

urlpatterns = [
    url(regex=r'^$', view=HomePage.as_view(), name='home_page')
]

vien_nchl/info/models.py
from django.db import models

# Create your models here.

vien_nchl/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

vien_nchl/web/models.py
import datetime
from uuid import uuid4

# Create your models here.
from django.db.models import Model, UUIDField, CharField, IntegerField, \
    ImageField, DateTimeField
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from parler.forms import TranslatableModelForm
from parler.models import TranslatableModel, TranslatedFields

STATUS_FIELD = ((1, 'Active'), (0, 'Inactive'))


class Slide(TranslatableModel):
    id = UUIDField(primary_key=True, default=uuid4)
    translations = TranslatedFields(
        name=CharField(_("Tiêu đề"), max_length=500, null=True, blank=True),
        description=CharField(_("Mô tả"), max_length=1000, null=True,
                              blank=True)
    )
    status = IntegerField(choices=STATUS_FIELD, default=0)
    image = ImageField(upload_to='upload/images')
    created_on = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Slide ảnh"
        verbose_name_plural = "Slide ảnh"

    def __str__(self):
        return self.name


class SlideForm(TranslatableModelForm):
    class Meta:
        model = Slide
        exclude = ['id', 'created_on', 'updated_at']


class Doctor(TranslatableModel):
    id = UUIDField(primary_key=True, default=uuid4)
    translations = TranslatedFields(
        name=CharField(_("Tên"), max_length=500),
        level=CharField(_("Học hàm học vị"), max_length=500),
        description=CharField(_("Mô tả"), max_length=2000)
    )
    image = ImageField(upload_to='upload/images')
    status = IntegerField(choices=STATUS_FIELD, default=0)
    created_on = DateTimeField(default=datetime.datetime.utcnow)
    updated_at = DateTimeField(auto_now=True)


    class Meta:
        verbose_name = "Danh sách bác sỹ"
        verbose_name_plural = "Danh sách bác sỹ"

    def __str__(self):
        return self.name


class DoctorForm(TranslatableModelForm):
    class Meta:
        model = Doctor
        exclude = ['id', 'created_on', 'updated_at']

vien_nchl/info/views.py
from django.shortcuts import render

# Create your views here.

vien_nchl/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

vien_nchl/web/views.py
# Create your views here.
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'web/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        return context

vien_nchl/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

vien_nchl/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}vien_nchl{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">vien_nchl</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

vien_nchl/templates/base_web.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% if not title %}{% trans "Viện nghiên cứu và đào tạo tiêu hoá gan mật" %}{% endif %}{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content=""/>
  <meta name="keywords" content=""/>
  <meta name="author" content=""/>

  <!-- Facebook and Twitter integration -->
  <meta property="og:title" content=""/>
  <meta property="og:image" content=""/>
  <meta property="og:url" content=""/>
  <meta property="og:site_name" content=""/>
  <meta property="og:description" content=""/>
  <meta name="twitter:title" content=""/>
  <meta name="twitter:image" content=""/>
  <meta name="twitter:url" content=""/>
  <meta name="twitter:card" content=""/>

  <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700"
    rel="stylesheet">
  {% block css %}
    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <!-- Flexslider  -->
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <!-- Flaticons  -->
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock css %}
  <!-- Modernizr JS -->
  <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
  <link rel="stylesheet"
        href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
        integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
        crossorigin="anonymous">
  <!-- FOR IE9 below -->
  <!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->
  <style>
    .container {
      padding-left: 7px;
      padding-right: 7px;
    }
  </style>
</head>
<body>
<div class="colorlib-loader"></div>
<div id="page" class="home">
  {% block header %}
  {% endblock header %}
  {% block content %}
  {% endblock content %}
  {% include 'footer.html' %}

</div>
{% block javascript %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- jQuery Easing -->
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Waypoints -->
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <!-- Stellar Parallax -->
  <script src="{% static  'js/jquery.stellar.min.js' %}"></script>
  <!-- Carousel -->
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <!-- Flexslider -->
  <script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
  <!-- countTo -->
  <script src="{% static 'js/jquery.countTo.js' %}"></script>
  <!-- Magnific Popup -->
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/magnific-popup-options.js' %}"></script>
  <!-- Sticky Kit -->
  <script src="{% static 'js/sticky-kit.min.js' %}"></script>
  <!-- Main -->
  <script src="{% static 'js/main.js' %}"></script>
{% endblock javascript %}
<script>
  function initMap() {
    // The location of Uluru
    var uluru = {lat: -25.344, lng: 131.036};
    // The map, centered at Uluru
    var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
    // The marker, positioned at Uluru
    var marker = new google.maps.Marker({position: uluru, map: map});
  }
</script>
<!--Load the API from the specified URL
* The async attribute allows the browser to render the page while the API loads
* The key parameter will contain your own API key (which is not needed for this tutorial)
* The callback parameter executes the initMap() function
-->
<script async defer
        src="https://maps.googleapis.com/maps/api/js?callback=initMap">
</script>
</body>
</html>

vien_nchl/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

vien_nchl/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

vien_nchl/templates/footer.html
{% load static i18n %}
{% block footer %}
  <footer id="colorlib-footer" role="contentinfo">
    <div class="overlay"></div>
    <div class="container">
      <div class="row row-pb-md">
        <div class="col-md-3 colorlib-widget">
          <h3>{% trans "Viện nghiên cứu và đào tạo tiêu hoá gan mật" %}</h3>
          <p>{% blocktrans %}Viện nghiên cứu và Đào tạo Tiêu hoá, Gan Mật theo yêu cầu đây là
            đơn vị đầu ngành sở hữu dàn máy nội soi và siêu âm nội soi hiện đại
            và tiên tiến
            bậc nhất hiện nay tại Việt Nam.Đào tạo bồi dưỡng cán bộ y tế ,
            hợp tác quốc tế{% endblocktrans %}</p>
        </div>
        <div class="col-md-2 colorlib-widget">
          <h3>{% trans "Điều hướng" %}</h3>
          <ul class="colorlib-footer-links">
            <li><a href="#"><i class="icon-check"></i>{% trans "Trang chủ" %}</a></li>
            <li><a href="#"><i class="icon-check"></i>{% trans "Giới thiệu" %} </a></li>
            <li><a href="#"><i class="icon-check"></i>{% trans "Nghiên cứu" %}</a></li>
            <li><a href="#"><i class="icon-check"></i>{% trans "Đào tạo" %}</a></li>
            <li><a href="#"><i class="icon-check"></i>{% trans "Tin tức" %}</a></li>
            <li><a href="#"><i class="icon-check"></i>{% trans "Liên hệ" %}</a></li>
          </ul>
        </div>
        <div class="col-md-2 colorlib-widget">
          <h3>{% trans "Liên hệ" %}</h3>
          <ul class="colorlib-footer-links">
            <li><a href="#"><i class="fab fa-facebook-f"></i>&nbsp;Facebook</a>
            </li>
            <li><a href="#"><i class="fab fa-google"></i>&nbsp;Google Plus</a>
            </li>
            <li><a href="#"><i class="fas fa-phone"></i>&nbsp;02462811337</a>
            </li>

          </ul>
        </div>
        <div class="col-md-5 colorlib-widget">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.601890460268!2d105.83558666461255!3d21.008589693843202!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab87801a5743%3A0xc8fc407c3c3ef8ec!2zUGjDsm5nIGtow6FtIMSQYSBraG9hIEhvw6BuZyBMb25n!5e0!3m2!1svi!2s!4v1530982815051"
            width="400" height="300" frameborder="0" style="border:0"
            allowfullscreen></iframe>
        </div>
      </div>
    </div>
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">
            Copyright ©
            <script>document.write(new Date().getFullYear());</script>
            All
            rights reserved | KDVTeam
          </small>
        </p>
      </div>
    </div>
  </footer>

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
  </div>
{% endblock %}

vien_nchl/templates/header.html
{% extends 'base_web.html' %}
{% block header %}
  {% load static i18n %}
  {% get_current_language as LANGUAGE_CODE %}
  <nav class="colorlib-nav" role="navigation">
    <div class="top-menu">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="top">
              <div class="row">
                <div class="col-md-3">
                  <div id="colorlib-logo">
                    <a href="index.html">
                      <div class="logo-lg" style="font-size: 20px">
                        <img
                          style="max-height:150px; max-width: 150px; display:
                           inline"
                          class="img-responsive"
                          {% if LANGUAGE_CODE == 'vi' %}
                          src="{% static 'images/logoIGH_Vietnamese.png' %}">
                          {% else %}
                          src="{% static 'images/logoIGH_English.png' %}">
                          {% endif %}
                      </div>
                      <div class="logo-mini">
                        <img
                          style="max-height:70px; max-width: 70px; display:
                          inline"
                          class="img-responsive"
                          {% if LANGUAGE_CODE == 'vi' %}
                          src="{% static 'images/logoIGH_Vietnamese.png' %}">
                          {% else %}
                          src="{% static 'images/logoIGH_English.png' %}">
                          {% endif %}
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="menu-wrap">
        <div class="container">
          <div class="row">
            <div class="col-xs-8">
              <div class="menu-1">
                <ul>
                  <li class="active"><a href="index.html">{%  trans "Trang chủ" %}</a></li>
                  <li><a href="about.html">{% trans "Giới thiệu" %}</a></li>
                  <li><a href="nghiencuu.html">{% trans "Nghiên cứu" %}</a></li>
                  <li><a href="daotao.html">{% trans "Đào tạo" %}</a></li>
                  <li><a href="tintuc.html">{% trans "Tin tức" %}</a></li>
                  <li><a href="lienhe.html">{% trans "Liên hệ" %}</a></li>
                </ul>
              </div>
            </div>
            <div class="col-md-4">
              <p class="btn-cta"><a href="appointment.html"><span>{% trans "Đăng ký khoá học" %}
                &nbsp;<i class="icon-calendar3"></i></span></a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <header class="header">
    <a href="/" class="header__logo"><img
                                          {% if LANGUAGE_CODE == 'vi' %}
                                          style="width: 73%; padding-left: 50px;"
                                          src="{% static 'images/logoIGH_Vietnamese.png' %}"
                                          {% else %}
                                          style="width: 88%; padding-left: 31px; margin-top: -25px"
                                          src="{% static 'images/logoIGH_English.png' %}"
                                          {% endif %}
                                          class="img-responsive"></a>
    <nav>
      <a class="nav-toggle" href="javascript:;" id="nav-toggle" title="Toggle Nav">
        <i></i>
        <i></i>
        <i></i>
      </a>
      <div class="nav-wrap">
        <ul class="nav">
          <li class="nav__link"><a style="padding: 0px 0px; color: white" href="index.html">{% trans "Trang chủ" %}</a></li>
          <li class="nav__link"><a style="padding: 0px 0px; color: white" href="about.html">{% trans "Giới thiệu" %}</a></li>
          <li class="nav__link"><a style="padding: 0px 0px; color: white" href="nghiencuu.html">{% trans "Nghiên cứu" %}</a></li>
          <li class="nav__link"><a style="padding: 0px 0px; color: white" href="daotao.html">{%  trans "Đào tạo" %}</a></li>
          <li class="nav__link"><a style="padding: 0px 0px; color: white" href="tintuc.html">{% trans "Tin tức" %}</a></li>
          <li class="nav__link"><a style="padding: 0px 0px; color: white" href="lienhe.html">{% trans "Liên hệ" %}</a></li>
        </ul>

        <ul class="utility-nav">
          <li>
            <a class="utility-nav__link" href=""><i class="icon-calendar3"></i>&nbsp;{% trans "Đăng ký khoá học" %}</a>
          </li>
        </ul><!-- /utility-nav -->

      </div><!-- /nav-wrap -->
    </nav>
  </header>
{% endblock %}

vien_nchl/templates/pages/about.html
{% extends "base.html" %}

vien_nchl/templates/pages/home.html
{% extends "base.html" %}

vien_nchl/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

vien_nchl/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

vien_nchl/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}